name: Compile Docker Images

on: 
  push:

jobs:
  main:
    strategy:
      matrix:
        args: [arm64, amd64]
    runs-on: ubuntu-20.04
    environment: development
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            suryatel/hm-miner
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: |
            type=sha,prefix=${{ matrix.args }}-
            type=sha,format=long,prefix=${{ matrix.args }}-
            type=ref,event=tag,prefix=${{ matrix.args }}-
            type=raw,value=${{ matrix.args }}-latest

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: BUILD_ARCH=${{ matrix.args }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=suryatel/hm-miner:buildcache
          cache-to: type=registry,ref=suryatel/hm-miner:buildcache,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
